name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        version: [14, 16, 18, 20]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use a more recent version of setup-node action
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm ci # Use npm ci for more reliable dependency installation

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest # GitHub Pages deployment typically works well on Ubuntu

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
